# Generated by Django 2.2 on 2020-10-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('ecom_vat', models.FloatField()),
                ('ecom_inside_dhaka_delivery_cost', models.IntegerField()),
                ('ecom_outside_dhaka_delivery_cost', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company')),
            ],
        ),
    ]
