# Generated by Django 2.2 on 2020-10-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_companyinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
