# Generated by Django 2.2 on 2020-10-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('ecom_vat', models.FloatField()),
                ('ecom_inside_dhaka_delivery_cost', models.IntegerField()),
                ('ecom_outside_dhaka_delivery_cost', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company_created_by', to='users.AuthUser')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company_modified_by', to='users.AuthUser')),
            ],
        ),
    ]
