# Generated by Django 3.1.2 on 2021-03-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_companyinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
